
#include "opengl33.h"
       
GLACTIVETEXTUREPROC glActiveTexture;
GLATTACHSHADERPROC glAttachShader;
GLBEGINCONDITIONALRENDERPROC glBeginConditionalRender;
GLBEGINQUERYPROC glBeginQuery;
GLBEGINTRANSFORMFEEDBACKPROC glBeginTransformFeedback;
GLBINDATTRIBLOCATIONPROC glBindAttribLocation;
GLBINDBUFFERPROC glBindBuffer;
GLBINDBUFFERBASEPROC glBindBufferBase;
GLBINDBUFFERRANGEPROC glBindBufferRange;
GLBINDFRAGDATALOCATIONPROC glBindFragDataLocation;
GLBINDFRAGDATALOCATIONINDEXEDPROC glBindFragDataLocationIndexed;
GLBINDFRAMEBUFFERPROC glBindFramebuffer;
GLBINDRENDERBUFFERPROC glBindRenderbuffer;
GLBINDSAMPLERPROC glBindSampler;
GLBINDTEXTUREPROC glBindTexture;
GLBINDVERTEXARRAYPROC glBindVertexArray;
GLBLENDCOLORPROC glBlendColor;
GLBLENDEQUATIONPROC glBlendEquation;
GLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate;
GLBLENDFUNCPROC glBlendFunc;
GLBLENDFUNCSEPARATEPROC glBlendFuncSeparate;
GLBLITFRAMEBUFFERPROC glBlitFramebuffer;
GLBUFFERDATAPROC glBufferData;
GLBUFFERSUBDATAPROC glBufferSubData;
GLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;
GLCLAMPCOLORPROC glClampColor;
GLCLEARPROC glClear;
GLCLEARBUFFERFIPROC glClearBufferfi;
GLCLEARBUFFERFVPROC glClearBufferfv;
GLCLEARBUFFERIVPROC glClearBufferiv;
GLCLEARBUFFERUIVPROC glClearBufferuiv;
GLCLEARCOLORPROC glClearColor;
GLCLEARDEPTHPROC glClearDepth;
GLCLEARSTENCILPROC glClearStencil;
GLCLIENTWAITSYNCPROC glClientWaitSync;
GLCOLORMASKPROC glColorMask;
GLCOLORMASKIPROC glColorMaski;
GLCOLORP3UIPROC glColorP3ui;
GLCOLORP3UIVPROC glColorP3uiv;
GLCOLORP4UIPROC glColorP4ui;
GLCOLORP4UIVPROC glColorP4uiv;
GLCOMPILESHADERPROC glCompileShader;
GLCOMPRESSEDTEXIMAGE1DPROC glCompressedTexImage1D;
GLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D;
GLCOMPRESSEDTEXIMAGE3DPROC glCompressedTexImage3D;
GLCOMPRESSEDTEXSUBIMAGE1DPROC glCompressedTexSubImage1D;
GLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D;
GLCOMPRESSEDTEXSUBIMAGE3DPROC glCompressedTexSubImage3D;
GLCOPYBUFFERSUBDATAPROC glCopyBufferSubData;
GLCOPYTEXIMAGE1DPROC glCopyTexImage1D;
GLCOPYTEXIMAGE2DPROC glCopyTexImage2D;
GLCOPYTEXSUBIMAGE1DPROC glCopyTexSubImage1D;
GLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D;
GLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D;
GLCREATEPROGRAMPROC glCreateProgram;
GLCREATESHADERPROC glCreateShader;
GLCULLFACEPROC glCullFace;
GLDELETEBUFFERSPROC glDeleteBuffers;
GLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
GLDELETEPROGRAMPROC glDeleteProgram;
GLDELETEQUERIESPROC glDeleteQueries;
GLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;
GLDELETESAMPLERSPROC glDeleteSamplers;
GLDELETESHADERPROC glDeleteShader;
GLDELETESYNCPROC glDeleteSync;
GLDELETETEXTURESPROC glDeleteTextures;
GLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;
GLDEPTHFUNCPROC glDepthFunc;
GLDEPTHMASKPROC glDepthMask;
GLDEPTHRANGEPROC glDepthRange;
GLDETACHSHADERPROC glDetachShader;
GLDISABLEPROC glDisable;
GLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
GLDISABLEIPROC glDisablei;
GLDRAWARRAYSPROC glDrawArrays;
GLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced;
GLDRAWBUFFERPROC glDrawBuffer;
GLDRAWBUFFERSPROC glDrawBuffers;
GLDRAWELEMENTSPROC glDrawElements;
GLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex;
GLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced;
GLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glDrawElementsInstancedBaseVertex;
GLDRAWRANGEELEMENTSPROC glDrawRangeElements;
GLDRAWRANGEELEMENTSBASEVERTEXPROC glDrawRangeElementsBaseVertex;
GLENABLEPROC glEnable;
GLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
GLENABLEIPROC glEnablei;
GLENDCONDITIONALRENDERPROC glEndConditionalRender;
GLENDQUERYPROC glEndQuery;
GLENDTRANSFORMFEEDBACKPROC glEndTransformFeedback;
GLFENCESYNCPROC glFenceSync;
GLFINISHPROC glFinish;
GLFLUSHPROC glFlush;
GLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange;
GLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
GLFRAMEBUFFERTEXTUREPROC glFramebufferTexture;
GLFRAMEBUFFERTEXTURE1DPROC glFramebufferTexture1D;
GLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
GLFRAMEBUFFERTEXTURE3DPROC glFramebufferTexture3D;
GLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer;
GLFRONTFACEPROC glFrontFace;
GLGENBUFFERSPROC glGenBuffers;
GLGENFRAMEBUFFERSPROC glGenFramebuffers;
GLGENQUERIESPROC glGenQueries;
GLGENRENDERBUFFERSPROC glGenRenderbuffers;
GLGENSAMPLERSPROC glGenSamplers;
GLGENTEXTURESPROC glGenTextures;
GLGENVERTEXARRAYSPROC glGenVertexArrays;
GLGENERATEMIPMAPPROC glGenerateMipmap;
GLGETACTIVEATTRIBPROC glGetActiveAttrib;
GLGETACTIVEUNIFORMPROC glGetActiveUniform;
GLGETACTIVEUNIFORMBLOCKNAMEPROC glGetActiveUniformBlockName;
GLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv;
GLGETACTIVEUNIFORMNAMEPROC glGetActiveUniformName;
GLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv;
GLGETATTACHEDSHADERSPROC glGetAttachedShaders;
GLGETATTRIBLOCATIONPROC glGetAttribLocation;
GLGETBOOLEANI_VPROC glGetBooleani_v;
GLGETBOOLEANVPROC glGetBooleanv;
GLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v;
GLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv;
GLGETBUFFERPOINTERVPROC glGetBufferPointerv;
GLGETBUFFERSUBDATAPROC glGetBufferSubData;
GLGETCOMPRESSEDTEXIMAGEPROC glGetCompressedTexImage;
GLGETDOUBLEVPROC glGetDoublev;
GLGETERRORPROC glGetError;
GLGETFLOATVPROC glGetFloatv;
GLGETFRAGDATAINDEXPROC glGetFragDataIndex;
GLGETFRAGDATALOCATIONPROC glGetFragDataLocation;
GLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv;
GLGETINTEGER64I_VPROC glGetInteger64i_v;
GLGETINTEGER64VPROC glGetInteger64v;
GLGETINTEGERI_VPROC glGetIntegeri_v;
GLGETINTEGERVPROC glGetIntegerv;
GLGETMULTISAMPLEFVPROC glGetMultisamplefv;
GLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
GLGETPROGRAMIVPROC glGetProgramiv;
GLGETQUERYOBJECTI64VPROC glGetQueryObjecti64v;
GLGETQUERYOBJECTIVPROC glGetQueryObjectiv;
GLGETQUERYOBJECTUI64VPROC glGetQueryObjectui64v;
GLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv;
GLGETQUERYIVPROC glGetQueryiv;
GLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv;
GLGETSAMPLERPARAMETERIIVPROC glGetSamplerParameterIiv;
GLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv;
GLGETSAMPLERPARAMETERFVPROC glGetSamplerParameterfv;
GLGETSAMPLERPARAMETERIVPROC glGetSamplerParameteriv;
GLGETSHADERINFOLOGPROC glGetShaderInfoLog;
GLGETSHADERSOURCEPROC glGetShaderSource;
GLGETSHADERIVPROC glGetShaderiv;
GLGETSTRINGPROC glGetString;
GLGETSTRINGIPROC glGetStringi;
GLGETSYNCIVPROC glGetSynciv;
GLGETTEXIMAGEPROC glGetTexImage;
GLGETTEXLEVELPARAMETERFVPROC glGetTexLevelParameterfv;
GLGETTEXLEVELPARAMETERIVPROC glGetTexLevelParameteriv;
GLGETTEXPARAMETERIIVPROC glGetTexParameterIiv;
GLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv;
GLGETTEXPARAMETERFVPROC glGetTexParameterfv;
GLGETTEXPARAMETERIVPROC glGetTexParameteriv;
GLGETTRANSFORMFEEDBACKVARYINGPROC glGetTransformFeedbackVarying;
GLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex;
GLGETUNIFORMINDICESPROC glGetUniformIndices;
GLGETUNIFORMLOCATIONPROC glGetUniformLocation;
GLGETUNIFORMFVPROC glGetUniformfv;
GLGETUNIFORMIVPROC glGetUniformiv;
GLGETUNIFORMUIVPROC glGetUniformuiv;
GLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv;
GLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv;
GLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv;
GLGETVERTEXATTRIBDVPROC glGetVertexAttribdv;
GLGETVERTEXATTRIBFVPROC glGetVertexAttribfv;
GLGETVERTEXATTRIBIVPROC glGetVertexAttribiv;
GLHINTPROC glHint;
GLISBUFFERPROC glIsBuffer;
GLISENABLEDPROC glIsEnabled;
GLISENABLEDIPROC glIsEnabledi;
GLISFRAMEBUFFERPROC glIsFramebuffer;
GLISPROGRAMPROC glIsProgram;
GLISQUERYPROC glIsQuery;
GLISRENDERBUFFERPROC glIsRenderbuffer;
GLISSAMPLERPROC glIsSampler;
GLISSHADERPROC glIsShader;
GLISSYNCPROC glIsSync;
GLISTEXTUREPROC glIsTexture;
GLISVERTEXARRAYPROC glIsVertexArray;
GLLINEWIDTHPROC glLineWidth;
GLLINKPROGRAMPROC glLinkProgram;
GLLOGICOPPROC glLogicOp;
GLMAPBUFFERPROC glMapBuffer;
GLMAPBUFFERRANGEPROC glMapBufferRange;
GLMULTIDRAWARRAYSPROC glMultiDrawArrays;
GLMULTIDRAWELEMENTSPROC glMultiDrawElements;
GLMULTIDRAWELEMENTSBASEVERTEXPROC glMultiDrawElementsBaseVertex;
GLMULTITEXCOORDP1UIPROC glMultiTexCoordP1ui;
GLMULTITEXCOORDP1UIVPROC glMultiTexCoordP1uiv;
GLMULTITEXCOORDP2UIPROC glMultiTexCoordP2ui;
GLMULTITEXCOORDP2UIVPROC glMultiTexCoordP2uiv;
GLMULTITEXCOORDP3UIPROC glMultiTexCoordP3ui;
GLMULTITEXCOORDP3UIVPROC glMultiTexCoordP3uiv;
GLMULTITEXCOORDP4UIPROC glMultiTexCoordP4ui;
GLMULTITEXCOORDP4UIVPROC glMultiTexCoordP4uiv;
GLNORMALP3UIPROC glNormalP3ui;
GLNORMALP3UIVPROC glNormalP3uiv;
GLPIXELSTOREFPROC glPixelStoref;
GLPIXELSTOREIPROC glPixelStorei;
GLPOINTPARAMETERFPROC glPointParameterf;
GLPOINTPARAMETERFVPROC glPointParameterfv;
GLPOINTPARAMETERIPROC glPointParameteri;
GLPOINTPARAMETERIVPROC glPointParameteriv;
GLPOINTSIZEPROC glPointSize;
GLPOLYGONMODEPROC glPolygonMode;
GLPOLYGONOFFSETPROC glPolygonOffset;
GLPRIMITIVERESTARTINDEXPROC glPrimitiveRestartIndex;
GLPROVOKINGVERTEXPROC glProvokingVertex;
GLQUERYCOUNTERPROC glQueryCounter;
GLREADBUFFERPROC glReadBuffer;
GLREADPIXELSPROC glReadPixels;
GLRENDERBUFFERSTORAGEPROC glRenderbufferStorage;
GLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample;
GLSAMPLECOVERAGEPROC glSampleCoverage;
GLSAMPLEMASKIPROC glSampleMaski;
GLSAMPLERPARAMETERIIVPROC glSamplerParameterIiv;
GLSAMPLERPARAMETERIUIVPROC glSamplerParameterIuiv;
GLSAMPLERPARAMETERFPROC glSamplerParameterf;
GLSAMPLERPARAMETERFVPROC glSamplerParameterfv;
GLSAMPLERPARAMETERIPROC glSamplerParameteri;
GLSAMPLERPARAMETERIVPROC glSamplerParameteriv;
GLSCISSORPROC glScissor;
GLSECONDARYCOLORP3UIPROC glSecondaryColorP3ui;
GLSECONDARYCOLORP3UIVPROC glSecondaryColorP3uiv;
GLSHADERSOURCEPROC glShaderSource;
GLSTENCILFUNCPROC glStencilFunc;
GLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate;
GLSTENCILMASKPROC glStencilMask;
GLSTENCILMASKSEPARATEPROC glStencilMaskSeparate;
GLSTENCILOPPROC glStencilOp;
GLSTENCILOPSEPARATEPROC glStencilOpSeparate;
GLTEXBUFFERPROC glTexBuffer;
GLTEXCOORDP1UIPROC glTexCoordP1ui;
GLTEXCOORDP1UIVPROC glTexCoordP1uiv;
GLTEXCOORDP2UIPROC glTexCoordP2ui;
GLTEXCOORDP2UIVPROC glTexCoordP2uiv;
GLTEXCOORDP3UIPROC glTexCoordP3ui;
GLTEXCOORDP3UIVPROC glTexCoordP3uiv;
GLTEXCOORDP4UIPROC glTexCoordP4ui;
GLTEXCOORDP4UIVPROC glTexCoordP4uiv;
GLTEXIMAGE1DPROC glTexImage1D;
GLTEXIMAGE2DPROC glTexImage2D;
GLTEXIMAGE2DMULTISAMPLEPROC glTexImage2DMultisample;
GLTEXIMAGE3DPROC glTexImage3D;
GLTEXIMAGE3DMULTISAMPLEPROC glTexImage3DMultisample;
GLTEXPARAMETERIIVPROC glTexParameterIiv;
GLTEXPARAMETERIUIVPROC glTexParameterIuiv;
GLTEXPARAMETERFPROC glTexParameterf;
GLTEXPARAMETERFVPROC glTexParameterfv;
GLTEXPARAMETERIPROC glTexParameteri;
GLTEXPARAMETERIVPROC glTexParameteriv;
GLTEXSUBIMAGE1DPROC glTexSubImage1D;
GLTEXSUBIMAGE2DPROC glTexSubImage2D;
GLTEXSUBIMAGE3DPROC glTexSubImage3D;
GLTRANSFORMFEEDBACKVARYINGSPROC glTransformFeedbackVaryings;
GLUNIFORM1FPROC glUniform1f;
GLUNIFORM1FVPROC glUniform1fv;
GLUNIFORM1IPROC glUniform1i;
GLUNIFORM1IVPROC glUniform1iv;
GLUNIFORM1UIPROC glUniform1ui;
GLUNIFORM1UIVPROC glUniform1uiv;
GLUNIFORM2FPROC glUniform2f;
GLUNIFORM2FVPROC glUniform2fv;
GLUNIFORM2IPROC glUniform2i;
GLUNIFORM2IVPROC glUniform2iv;
GLUNIFORM2UIPROC glUniform2ui;
GLUNIFORM2UIVPROC glUniform2uiv;
GLUNIFORM3FPROC glUniform3f;
GLUNIFORM3FVPROC glUniform3fv;
GLUNIFORM3IPROC glUniform3i;
GLUNIFORM3IVPROC glUniform3iv;
GLUNIFORM3UIPROC glUniform3ui;
GLUNIFORM3UIVPROC glUniform3uiv;
GLUNIFORM4FPROC glUniform4f;
GLUNIFORM4FVPROC glUniform4fv;
GLUNIFORM4IPROC glUniform4i;
GLUNIFORM4IVPROC glUniform4iv;
GLUNIFORM4UIPROC glUniform4ui;
GLUNIFORM4UIVPROC glUniform4uiv;
GLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding;
GLUNIFORMMATRIX2FVPROC glUniformMatrix2fv;
GLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv;
GLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv;
GLUNIFORMMATRIX3FVPROC glUniformMatrix3fv;
GLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv;
GLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv;
GLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
GLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv;
GLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv;
GLUNMAPBUFFERPROC glUnmapBuffer;
GLUSEPROGRAMPROC glUseProgram;
GLVALIDATEPROGRAMPROC glValidateProgram;
GLVERTEXATTRIB1DPROC glVertexAttrib1d;
GLVERTEXATTRIB1DVPROC glVertexAttrib1dv;
GLVERTEXATTRIB1FPROC glVertexAttrib1f;
GLVERTEXATTRIB1FVPROC glVertexAttrib1fv;
GLVERTEXATTRIB1SPROC glVertexAttrib1s;
GLVERTEXATTRIB1SVPROC glVertexAttrib1sv;
GLVERTEXATTRIB2DPROC glVertexAttrib2d;
GLVERTEXATTRIB2DVPROC glVertexAttrib2dv;
GLVERTEXATTRIB2FPROC glVertexAttrib2f;
GLVERTEXATTRIB2FVPROC glVertexAttrib2fv;
GLVERTEXATTRIB2SPROC glVertexAttrib2s;
GLVERTEXATTRIB2SVPROC glVertexAttrib2sv;
GLVERTEXATTRIB3DPROC glVertexAttrib3d;
GLVERTEXATTRIB3DVPROC glVertexAttrib3dv;
GLVERTEXATTRIB3FPROC glVertexAttrib3f;
GLVERTEXATTRIB3FVPROC glVertexAttrib3fv;
GLVERTEXATTRIB3SPROC glVertexAttrib3s;
GLVERTEXATTRIB3SVPROC glVertexAttrib3sv;
GLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv;
GLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv;
GLVERTEXATTRIB4NSVPROC glVertexAttrib4Nsv;
GLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub;
GLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv;
GLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv;
GLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv;
GLVERTEXATTRIB4BVPROC glVertexAttrib4bv;
GLVERTEXATTRIB4DPROC glVertexAttrib4d;
GLVERTEXATTRIB4DVPROC glVertexAttrib4dv;
GLVERTEXATTRIB4FPROC glVertexAttrib4f;
GLVERTEXATTRIB4FVPROC glVertexAttrib4fv;
GLVERTEXATTRIB4IVPROC glVertexAttrib4iv;
GLVERTEXATTRIB4SPROC glVertexAttrib4s;
GLVERTEXATTRIB4SVPROC glVertexAttrib4sv;
GLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv;
GLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv;
GLVERTEXATTRIB4USVPROC glVertexAttrib4usv;
GLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor;
GLVERTEXATTRIBI1IPROC glVertexAttribI1i;
GLVERTEXATTRIBI1IVPROC glVertexAttribI1iv;
GLVERTEXATTRIBI1UIPROC glVertexAttribI1ui;
GLVERTEXATTRIBI1UIVPROC glVertexAttribI1uiv;
GLVERTEXATTRIBI2IPROC glVertexAttribI2i;
GLVERTEXATTRIBI2IVPROC glVertexAttribI2iv;
GLVERTEXATTRIBI2UIPROC glVertexAttribI2ui;
GLVERTEXATTRIBI2UIVPROC glVertexAttribI2uiv;
GLVERTEXATTRIBI3IPROC glVertexAttribI3i;
GLVERTEXATTRIBI3IVPROC glVertexAttribI3iv;
GLVERTEXATTRIBI3UIPROC glVertexAttribI3ui;
GLVERTEXATTRIBI3UIVPROC glVertexAttribI3uiv;
GLVERTEXATTRIBI4BVPROC glVertexAttribI4bv;
GLVERTEXATTRIBI4IPROC glVertexAttribI4i;
GLVERTEXATTRIBI4IVPROC glVertexAttribI4iv;
GLVERTEXATTRIBI4SVPROC glVertexAttribI4sv;
GLVERTEXATTRIBI4UBVPROC glVertexAttribI4ubv;
GLVERTEXATTRIBI4UIPROC glVertexAttribI4ui;
GLVERTEXATTRIBI4UIVPROC glVertexAttribI4uiv;
GLVERTEXATTRIBI4USVPROC glVertexAttribI4usv;
GLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer;
GLVERTEXATTRIBP1UIPROC glVertexAttribP1ui;
GLVERTEXATTRIBP1UIVPROC glVertexAttribP1uiv;
GLVERTEXATTRIBP2UIPROC glVertexAttribP2ui;
GLVERTEXATTRIBP2UIVPROC glVertexAttribP2uiv;
GLVERTEXATTRIBP3UIPROC glVertexAttribP3ui;
GLVERTEXATTRIBP3UIVPROC glVertexAttribP3uiv;
GLVERTEXATTRIBP4UIPROC glVertexAttribP4ui;
GLVERTEXATTRIBP4UIVPROC glVertexAttribP4uiv;
GLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
GLVERTEXP2UIPROC glVertexP2ui;
GLVERTEXP2UIVPROC glVertexP2uiv;
GLVERTEXP3UIPROC glVertexP3ui;
GLVERTEXP3UIVPROC glVertexP3uiv;
GLVERTEXP4UIPROC glVertexP4ui;
GLVERTEXP4UIVPROC glVertexP4uiv;
GLVIEWPORTPROC glViewport;
GLWAITSYNCPROC glWaitSync;

void init_openg33()
{


    glActiveTexture=(GLACTIVETEXTUREPROC)wglGetProcAddress("glActiveTexture");
    glAttachShader=(GLATTACHSHADERPROC)wglGetProcAddress("glAttachShader");
    glBeginConditionalRender=(GLBEGINCONDITIONALRENDERPROC)wglGetProcAddress("glBeginConditionalRender");
    glBeginQuery=(GLBEGINQUERYPROC)wglGetProcAddress("glBeginQuery");
    glBeginTransformFeedback=(GLBEGINTRANSFORMFEEDBACKPROC)wglGetProcAddress("glBeginTransformFeedback");
    glBindAttribLocation=(GLBINDATTRIBLOCATIONPROC)wglGetProcAddress("glBindAttribLocation");
    glBindBuffer=(GLBINDBUFFERPROC)wglGetProcAddress("glBindBuffer");
    glBindBufferBase=(GLBINDBUFFERBASEPROC)wglGetProcAddress("glBindBufferBase");
    glBindBufferRange=(GLBINDBUFFERRANGEPROC)wglGetProcAddress("glBindBufferRange");
    glBindFragDataLocation=(GLBINDFRAGDATALOCATIONPROC)wglGetProcAddress("glBindFragDataLocation");
    glBindFragDataLocationIndexed=(GLBINDFRAGDATALOCATIONINDEXEDPROC)wglGetProcAddress("glBindFragDataLocationIndexed");
    glBindFramebuffer=(GLBINDFRAMEBUFFERPROC)wglGetProcAddress("glBindFramebuffer");
    glBindRenderbuffer=(GLBINDRENDERBUFFERPROC)wglGetProcAddress("glBindRenderbuffer");
    glBindSampler=(GLBINDSAMPLERPROC)wglGetProcAddress("glBindSampler");
    glBindTexture=(GLBINDTEXTUREPROC)wglGetProcAddress("glBindTexture");
    glBindVertexArray=(GLBINDVERTEXARRAYPROC)wglGetProcAddress("glBindVertexArray");
    glBlendColor=(GLBLENDCOLORPROC)wglGetProcAddress("glBlendColor");
    glBlendEquation=(GLBLENDEQUATIONPROC)wglGetProcAddress("glBlendEquation");
    glBlendEquationSeparate=(GLBLENDEQUATIONSEPARATEPROC)wglGetProcAddress("glBlendEquationSeparate");
    glBlendFunc=(GLBLENDFUNCPROC)wglGetProcAddress("glBlendFunc");
    glBlendFuncSeparate=(GLBLENDFUNCSEPARATEPROC)wglGetProcAddress("glBlendFuncSeparate");
    glBlitFramebuffer=(GLBLITFRAMEBUFFERPROC)wglGetProcAddress("glBlitFramebuffer");
    glBufferData=(GLBUFFERDATAPROC)wglGetProcAddress("glBufferData");
    glBufferSubData=(GLBUFFERSUBDATAPROC)wglGetProcAddress("glBufferSubData");
    glCheckFramebufferStatus=(GLCHECKFRAMEBUFFERSTATUSPROC)wglGetProcAddress("glCheckFramebufferStatus");
    glClampColor=(GLCLAMPCOLORPROC)wglGetProcAddress("glClampColor");
    glClear=(GLCLEARPROC)wglGetProcAddress("glClear");
    glClearBufferfi=(GLCLEARBUFFERFIPROC)wglGetProcAddress("glClearBufferfi");
    glClearBufferfv=(GLCLEARBUFFERFVPROC)wglGetProcAddress("glClearBufferfv");
    glClearBufferiv=(GLCLEARBUFFERIVPROC)wglGetProcAddress("glClearBufferiv");
    glClearBufferuiv=(GLCLEARBUFFERUIVPROC)wglGetProcAddress("glClearBufferuiv");
    glClearColor=(GLCLEARCOLORPROC)wglGetProcAddress("glClearColor");
    glClearDepth=(GLCLEARDEPTHPROC)wglGetProcAddress("glClearDepth");
    glClearStencil=(GLCLEARSTENCILPROC)wglGetProcAddress("glClearStencil");
    glClientWaitSync=(GLCLIENTWAITSYNCPROC)wglGetProcAddress("glClientWaitSync");
    glColorMask=(GLCOLORMASKPROC)wglGetProcAddress("glColorMask");
    glColorMaski=(GLCOLORMASKIPROC)wglGetProcAddress("glColorMaski");
    glColorP3ui=(GLCOLORP3UIPROC)wglGetProcAddress("glColorP3ui");
    glColorP3uiv=(GLCOLORP3UIVPROC)wglGetProcAddress("glColorP3uiv");
    glColorP4ui=(GLCOLORP4UIPROC)wglGetProcAddress("glColorP4ui");
    glColorP4uiv=(GLCOLORP4UIVPROC)wglGetProcAddress("glColorP4uiv");
    glCompileShader=(GLCOMPILESHADERPROC)wglGetProcAddress("glCompileShader");
    glCompressedTexImage1D=(GLCOMPRESSEDTEXIMAGE1DPROC)wglGetProcAddress("glCompressedTexImage1D");
    glCompressedTexImage2D=(GLCOMPRESSEDTEXIMAGE2DPROC)wglGetProcAddress("glCompressedTexImage2D");
    glCompressedTexImage3D=(GLCOMPRESSEDTEXIMAGE3DPROC)wglGetProcAddress("glCompressedTexImage3D");
    glCompressedTexSubImage1D=(GLCOMPRESSEDTEXSUBIMAGE1DPROC)wglGetProcAddress("glCompressedTexSubImage1D");
    glCompressedTexSubImage2D=(GLCOMPRESSEDTEXSUBIMAGE2DPROC)wglGetProcAddress("glCompressedTexSubImage2D");
    glCompressedTexSubImage3D=(GLCOMPRESSEDTEXSUBIMAGE3DPROC)wglGetProcAddress("glCompressedTexSubImage3D");
    glCopyBufferSubData=(GLCOPYBUFFERSUBDATAPROC)wglGetProcAddress("glCopyBufferSubData");
    glCopyTexImage1D=(GLCOPYTEXIMAGE1DPROC)wglGetProcAddress("glCopyTexImage1D");
    glCopyTexImage2D=(GLCOPYTEXIMAGE2DPROC)wglGetProcAddress("glCopyTexImage2D");
    glCopyTexSubImage1D=(GLCOPYTEXSUBIMAGE1DPROC)wglGetProcAddress("glCopyTexSubImage1D");
    glCopyTexSubImage2D=(GLCOPYTEXSUBIMAGE2DPROC)wglGetProcAddress("glCopyTexSubImage2D");
    glCopyTexSubImage3D=(GLCOPYTEXSUBIMAGE3DPROC)wglGetProcAddress("glCopyTexSubImage3D");
    glCreateProgram=(GLCREATEPROGRAMPROC)wglGetProcAddress("glCreateProgram");
    glCreateShader=(GLCREATESHADERPROC)wglGetProcAddress("glCreateShader");
    glCullFace=(GLCULLFACEPROC)wglGetProcAddress("glCullFace");
    glDeleteBuffers=(GLDELETEBUFFERSPROC)wglGetProcAddress("glDeleteBuffers");
    glDeleteFramebuffers=(GLDELETEFRAMEBUFFERSPROC)wglGetProcAddress("glDeleteFramebuffers");
    glDeleteProgram=(GLDELETEPROGRAMPROC)wglGetProcAddress("glDeleteProgram");
    glDeleteQueries=(GLDELETEQUERIESPROC)wglGetProcAddress("glDeleteQueries");
    glDeleteRenderbuffers=(GLDELETERENDERBUFFERSPROC)wglGetProcAddress("glDeleteRenderbuffers");
    glDeleteSamplers=(GLDELETESAMPLERSPROC)wglGetProcAddress("glDeleteSamplers");
    glDeleteShader=(GLDELETESHADERPROC)wglGetProcAddress("glDeleteShader");
    glDeleteSync=(GLDELETESYNCPROC)wglGetProcAddress("glDeleteSync");
    glDeleteTextures=(GLDELETETEXTURESPROC)wglGetProcAddress("glDeleteTextures");
    glDeleteVertexArrays=(GLDELETEVERTEXARRAYSPROC)wglGetProcAddress("glDeleteVertexArrays");
    glDepthFunc=(GLDEPTHFUNCPROC)wglGetProcAddress("glDepthFunc");
    glDepthMask=(GLDEPTHMASKPROC)wglGetProcAddress("glDepthMask");
    glDepthRange=(GLDEPTHRANGEPROC)wglGetProcAddress("glDepthRange");
    glDetachShader=(GLDETACHSHADERPROC)wglGetProcAddress("glDetachShader");
    glDisable=(GLDISABLEPROC)wglGetProcAddress("glDisable");
    glDisableVertexAttribArray=(GLDISABLEVERTEXATTRIBARRAYPROC)wglGetProcAddress("glDisableVertexAttribArray");
    glDisablei=(GLDISABLEIPROC)wglGetProcAddress("glDisablei");
    glDrawArrays=(GLDRAWARRAYSPROC)wglGetProcAddress("glDrawArrays");
    glDrawArraysInstanced=(GLDRAWARRAYSINSTANCEDPROC)wglGetProcAddress("glDrawArraysInstanced");
    glDrawBuffer=(GLDRAWBUFFERPROC)wglGetProcAddress("glDrawBuffer");
    glDrawBuffers=(GLDRAWBUFFERSPROC)wglGetProcAddress("glDrawBuffers");
    glDrawElements=(GLDRAWELEMENTSPROC)wglGetProcAddress("glDrawElements");
    glDrawElementsBaseVertex=(GLDRAWELEMENTSBASEVERTEXPROC)wglGetProcAddress("glDrawElementsBaseVertex");
    glDrawElementsInstanced=(GLDRAWELEMENTSINSTANCEDPROC)wglGetProcAddress("glDrawElementsInstanced");
    glDrawElementsInstancedBaseVertex=(GLDRAWELEMENTSINSTANCEDBASEVERTEXPROC)wglGetProcAddress("glDrawElementsInstancedBaseVertex");
    glDrawRangeElements=(GLDRAWRANGEELEMENTSPROC)wglGetProcAddress("glDrawRangeElements");
    glDrawRangeElementsBaseVertex=(GLDRAWRANGEELEMENTSBASEVERTEXPROC)wglGetProcAddress("glDrawRangeElementsBaseVertex");
    glEnable=(GLENABLEPROC)wglGetProcAddress("glEnable");
    glEnableVertexAttribArray=(GLENABLEVERTEXATTRIBARRAYPROC)wglGetProcAddress("glEnableVertexAttribArray");
    glEnablei=(GLENABLEIPROC)wglGetProcAddress("glEnablei");
    glEndConditionalRender=(GLENDCONDITIONALRENDERPROC)wglGetProcAddress("glEndConditionalRender");
    glEndQuery=(GLENDQUERYPROC)wglGetProcAddress("glEndQuery");
    glEndTransformFeedback=(GLENDTRANSFORMFEEDBACKPROC)wglGetProcAddress("glEndTransformFeedback");
    glFenceSync=(GLFENCESYNCPROC)wglGetProcAddress("glFenceSync");
    glFinish=(GLFINISHPROC)wglGetProcAddress("glFinish");
    glFlush=(GLFLUSHPROC)wglGetProcAddress("glFlush");
    glFlushMappedBufferRange=(GLFLUSHMAPPEDBUFFERRANGEPROC)wglGetProcAddress("glFlushMappedBufferRange");
    glFramebufferRenderbuffer=(GLFRAMEBUFFERRENDERBUFFERPROC)wglGetProcAddress("glFramebufferRenderbuffer");
    glFramebufferTexture=(GLFRAMEBUFFERTEXTUREPROC)wglGetProcAddress("glFramebufferTexture");
    glFramebufferTexture1D=(GLFRAMEBUFFERTEXTURE1DPROC)wglGetProcAddress("glFramebufferTexture1D");
    glFramebufferTexture2D=(GLFRAMEBUFFERTEXTURE2DPROC)wglGetProcAddress("glFramebufferTexture2D");
    glFramebufferTexture3D=(GLFRAMEBUFFERTEXTURE3DPROC)wglGetProcAddress("glFramebufferTexture3D");
    glFramebufferTextureLayer=(GLFRAMEBUFFERTEXTURELAYERPROC)wglGetProcAddress("glFramebufferTextureLayer");
    glFrontFace=(GLFRONTFACEPROC)wglGetProcAddress("glFrontFace");
    glGenBuffers=(GLGENBUFFERSPROC)wglGetProcAddress("glGenBuffers");
    glGenFramebuffers=(GLGENFRAMEBUFFERSPROC)wglGetProcAddress("glGenFramebuffers");
    glGenQueries=(GLGENQUERIESPROC)wglGetProcAddress("glGenQueries");
    glGenRenderbuffers=(GLGENRENDERBUFFERSPROC)wglGetProcAddress("glGenRenderbuffers");
    glGenSamplers=(GLGENSAMPLERSPROC)wglGetProcAddress("glGenSamplers");
    glGenTextures=(GLGENTEXTURESPROC)wglGetProcAddress("glGenTextures");
    glGenVertexArrays=(GLGENVERTEXARRAYSPROC)wglGetProcAddress("glGenVertexArrays");
    glGenerateMipmap=(GLGENERATEMIPMAPPROC)wglGetProcAddress("glGenerateMipmap");
    glGetActiveAttrib=(GLGETACTIVEATTRIBPROC)wglGetProcAddress("glGetActiveAttrib");
    glGetActiveUniform=(GLGETACTIVEUNIFORMPROC)wglGetProcAddress("glGetActiveUniform");
    glGetActiveUniformBlockName=(GLGETACTIVEUNIFORMBLOCKNAMEPROC)wglGetProcAddress("glGetActiveUniformBlockName");
    glGetActiveUniformBlockiv=(GLGETACTIVEUNIFORMBLOCKIVPROC)wglGetProcAddress("glGetActiveUniformBlockiv");
    glGetActiveUniformName=(GLGETACTIVEUNIFORMNAMEPROC)wglGetProcAddress("glGetActiveUniformName");
    glGetActiveUniformsiv=(GLGETACTIVEUNIFORMSIVPROC)wglGetProcAddress("glGetActiveUniformsiv");
    glGetAttachedShaders=(GLGETATTACHEDSHADERSPROC)wglGetProcAddress("glGetAttachedShaders");
    glGetAttribLocation=(GLGETATTRIBLOCATIONPROC)wglGetProcAddress("glGetAttribLocation");
    glGetBooleani_v=(GLGETBOOLEANI_VPROC)wglGetProcAddress("glGetBooleani_v");
    glGetBooleanv=(GLGETBOOLEANVPROC)wglGetProcAddress("glGetBooleanv");
    glGetBufferParameteri64v=(GLGETBUFFERPARAMETERI64VPROC)wglGetProcAddress("glGetBufferParameteri64v");
    glGetBufferParameteriv=(GLGETBUFFERPARAMETERIVPROC)wglGetProcAddress("glGetBufferParameteriv");
    glGetBufferPointerv=(GLGETBUFFERPOINTERVPROC)wglGetProcAddress("glGetBufferPointerv");
    glGetBufferSubData=(GLGETBUFFERSUBDATAPROC)wglGetProcAddress("glGetBufferSubData");
    glGetCompressedTexImage=(GLGETCOMPRESSEDTEXIMAGEPROC)wglGetProcAddress("glGetCompressedTexImage");
    glGetDoublev=(GLGETDOUBLEVPROC)wglGetProcAddress("glGetDoublev");
    glGetError=(GLGETERRORPROC)wglGetProcAddress("glGetError");
    glGetFloatv=(GLGETFLOATVPROC)wglGetProcAddress("glGetFloatv");
    glGetFragDataIndex=(GLGETFRAGDATAINDEXPROC)wglGetProcAddress("glGetFragDataIndex");
    glGetFragDataLocation=(GLGETFRAGDATALOCATIONPROC)wglGetProcAddress("glGetFragDataLocation");
    glGetFramebufferAttachmentParameteriv=(GLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)wglGetProcAddress("glGetFramebufferAttachmentParameteriv");
    glGetInteger64i_v=(GLGETINTEGER64I_VPROC)wglGetProcAddress("glGetInteger64i_v");
    glGetInteger64v=(GLGETINTEGER64VPROC)wglGetProcAddress("glGetInteger64v");
    glGetIntegeri_v=(GLGETINTEGERI_VPROC)wglGetProcAddress("glGetIntegeri_v");
    glGetIntegerv=(GLGETINTEGERVPROC)wglGetProcAddress("glGetIntegerv");
    glGetMultisamplefv=(GLGETMULTISAMPLEFVPROC)wglGetProcAddress("glGetMultisamplefv");
    glGetProgramInfoLog=(GLGETPROGRAMINFOLOGPROC)wglGetProcAddress("glGetProgramInfoLog");
    glGetProgramiv=(GLGETPROGRAMIVPROC)wglGetProcAddress("glGetProgramiv");
    glGetQueryObjecti64v=(GLGETQUERYOBJECTI64VPROC)wglGetProcAddress("glGetQueryObjecti64v");
    glGetQueryObjectiv=(GLGETQUERYOBJECTIVPROC)wglGetProcAddress("glGetQueryObjectiv");
    glGetQueryObjectui64v=(GLGETQUERYOBJECTUI64VPROC)wglGetProcAddress("glGetQueryObjectui64v");
    glGetQueryObjectuiv=(GLGETQUERYOBJECTUIVPROC)wglGetProcAddress("glGetQueryObjectuiv");
    glGetQueryiv=(GLGETQUERYIVPROC)wglGetProcAddress("glGetQueryiv");
    glGetRenderbufferParameteriv=(GLGETRENDERBUFFERPARAMETERIVPROC)wglGetProcAddress("glGetRenderbufferParameteriv");
    glGetSamplerParameterIiv=(GLGETSAMPLERPARAMETERIIVPROC)wglGetProcAddress("glGetSamplerParameterIiv");
    glGetSamplerParameterIuiv=(GLGETSAMPLERPARAMETERIUIVPROC)wglGetProcAddress("glGetSamplerParameterIuiv");
    glGetSamplerParameterfv=(GLGETSAMPLERPARAMETERFVPROC)wglGetProcAddress("glGetSamplerParameterfv");
    glGetSamplerParameteriv=(GLGETSAMPLERPARAMETERIVPROC)wglGetProcAddress("glGetSamplerParameteriv");
    glGetShaderInfoLog=(GLGETSHADERINFOLOGPROC)wglGetProcAddress("glGetShaderInfoLog");
    glGetShaderSource=(GLGETSHADERSOURCEPROC)wglGetProcAddress("glGetShaderSource");
    glGetShaderiv=(GLGETSHADERIVPROC)wglGetProcAddress("glGetShaderiv");
    glGetString=(GLGETSTRINGPROC)wglGetProcAddress("glGetString");
    glGetStringi=(GLGETSTRINGIPROC)wglGetProcAddress("glGetStringi");
    glGetSynciv=(GLGETSYNCIVPROC)wglGetProcAddress("glGetSynciv");
    glGetTexImage=(GLGETTEXIMAGEPROC)wglGetProcAddress("glGetTexImage");
    glGetTexLevelParameterfv=(GLGETTEXLEVELPARAMETERFVPROC)wglGetProcAddress("glGetTexLevelParameterfv");
    glGetTexLevelParameteriv=(GLGETTEXLEVELPARAMETERIVPROC)wglGetProcAddress("glGetTexLevelParameteriv");
    glGetTexParameterIiv=(GLGETTEXPARAMETERIIVPROC)wglGetProcAddress("glGetTexParameterIiv");
    glGetTexParameterIuiv=(GLGETTEXPARAMETERIUIVPROC)wglGetProcAddress("glGetTexParameterIuiv");
    glGetTexParameterfv=(GLGETTEXPARAMETERFVPROC)wglGetProcAddress("glGetTexParameterfv");
    glGetTexParameteriv=(GLGETTEXPARAMETERIVPROC)wglGetProcAddress("glGetTexParameteriv");
    glGetTransformFeedbackVarying=(GLGETTRANSFORMFEEDBACKVARYINGPROC)wglGetProcAddress("glGetTransformFeedbackVarying");
    glGetUniformBlockIndex=(GLGETUNIFORMBLOCKINDEXPROC)wglGetProcAddress("glGetUniformBlockIndex");
    glGetUniformIndices=(GLGETUNIFORMINDICESPROC)wglGetProcAddress("glGetUniformIndices");
    glGetUniformLocation=(GLGETUNIFORMLOCATIONPROC)wglGetProcAddress("glGetUniformLocation");
    glGetUniformfv=(GLGETUNIFORMFVPROC)wglGetProcAddress("glGetUniformfv");
    glGetUniformiv=(GLGETUNIFORMIVPROC)wglGetProcAddress("glGetUniformiv");
    glGetUniformuiv=(GLGETUNIFORMUIVPROC)wglGetProcAddress("glGetUniformuiv");
    glGetVertexAttribIiv=(GLGETVERTEXATTRIBIIVPROC)wglGetProcAddress("glGetVertexAttribIiv");
    glGetVertexAttribIuiv=(GLGETVERTEXATTRIBIUIVPROC)wglGetProcAddress("glGetVertexAttribIuiv");
    glGetVertexAttribPointerv=(GLGETVERTEXATTRIBPOINTERVPROC)wglGetProcAddress("glGetVertexAttribPointerv");
    glGetVertexAttribdv=(GLGETVERTEXATTRIBDVPROC)wglGetProcAddress("glGetVertexAttribdv");
    glGetVertexAttribfv=(GLGETVERTEXATTRIBFVPROC)wglGetProcAddress("glGetVertexAttribfv");
    glGetVertexAttribiv=(GLGETVERTEXATTRIBIVPROC)wglGetProcAddress("glGetVertexAttribiv");
    glHint=(GLHINTPROC)wglGetProcAddress("glHint");
    glIsBuffer=(GLISBUFFERPROC)wglGetProcAddress("glIsBuffer");
    glIsEnabled=(GLISENABLEDPROC)wglGetProcAddress("glIsEnabled");
    glIsEnabledi=(GLISENABLEDIPROC)wglGetProcAddress("glIsEnabledi");
    glIsFramebuffer=(GLISFRAMEBUFFERPROC)wglGetProcAddress("glIsFramebuffer");
    glIsProgram=(GLISPROGRAMPROC)wglGetProcAddress("glIsProgram");
    glIsQuery=(GLISQUERYPROC)wglGetProcAddress("glIsQuery");
    glIsRenderbuffer=(GLISRENDERBUFFERPROC)wglGetProcAddress("glIsRenderbuffer");
    glIsSampler=(GLISSAMPLERPROC)wglGetProcAddress("glIsSampler");
    glIsShader=(GLISSHADERPROC)wglGetProcAddress("glIsShader");
    glIsSync=(GLISSYNCPROC)wglGetProcAddress("glIsSync");
    glIsTexture=(GLISTEXTUREPROC)wglGetProcAddress("glIsTexture");
    glIsVertexArray=(GLISVERTEXARRAYPROC)wglGetProcAddress("glIsVertexArray");
    glLineWidth=(GLLINEWIDTHPROC)wglGetProcAddress("glLineWidth");
    glLinkProgram=(GLLINKPROGRAMPROC)wglGetProcAddress("glLinkProgram");
    glLogicOp=(GLLOGICOPPROC)wglGetProcAddress("glLogicOp");
    glMapBuffer=(GLMAPBUFFERPROC)wglGetProcAddress("glMapBuffer");
    glMapBufferRange=(GLMAPBUFFERRANGEPROC)wglGetProcAddress("glMapBufferRange");
    glMultiDrawArrays=(GLMULTIDRAWARRAYSPROC)wglGetProcAddress("glMultiDrawArrays");
    glMultiDrawElements=(GLMULTIDRAWELEMENTSPROC)wglGetProcAddress("glMultiDrawElements");
    glMultiDrawElementsBaseVertex=(GLMULTIDRAWELEMENTSBASEVERTEXPROC)wglGetProcAddress("glMultiDrawElementsBaseVertex");
    glMultiTexCoordP1ui=(GLMULTITEXCOORDP1UIPROC)wglGetProcAddress("glMultiTexCoordP1ui");
    glMultiTexCoordP1uiv=(GLMULTITEXCOORDP1UIVPROC)wglGetProcAddress("glMultiTexCoordP1uiv");
    glMultiTexCoordP2ui=(GLMULTITEXCOORDP2UIPROC)wglGetProcAddress("glMultiTexCoordP2ui");
    glMultiTexCoordP2uiv=(GLMULTITEXCOORDP2UIVPROC)wglGetProcAddress("glMultiTexCoordP2uiv");
    glMultiTexCoordP3ui=(GLMULTITEXCOORDP3UIPROC)wglGetProcAddress("glMultiTexCoordP3ui");
    glMultiTexCoordP3uiv=(GLMULTITEXCOORDP3UIVPROC)wglGetProcAddress("glMultiTexCoordP3uiv");
    glMultiTexCoordP4ui=(GLMULTITEXCOORDP4UIPROC)wglGetProcAddress("glMultiTexCoordP4ui");
    glMultiTexCoordP4uiv=(GLMULTITEXCOORDP4UIVPROC)wglGetProcAddress("glMultiTexCoordP4uiv");
    glNormalP3ui=(GLNORMALP3UIPROC)wglGetProcAddress("glNormalP3ui");
    glNormalP3uiv=(GLNORMALP3UIVPROC)wglGetProcAddress("glNormalP3uiv");
    glPixelStoref=(GLPIXELSTOREFPROC)wglGetProcAddress("glPixelStoref");
    glPixelStorei=(GLPIXELSTOREIPROC)wglGetProcAddress("glPixelStorei");
    glPointParameterf=(GLPOINTPARAMETERFPROC)wglGetProcAddress("glPointParameterf");
    glPointParameterfv=(GLPOINTPARAMETERFVPROC)wglGetProcAddress("glPointParameterfv");
    glPointParameteri=(GLPOINTPARAMETERIPROC)wglGetProcAddress("glPointParameteri");
    glPointParameteriv=(GLPOINTPARAMETERIVPROC)wglGetProcAddress("glPointParameteriv");
    glPointSize=(GLPOINTSIZEPROC)wglGetProcAddress("glPointSize");
    glPolygonMode=(GLPOLYGONMODEPROC)wglGetProcAddress("glPolygonMode");
    glPolygonOffset=(GLPOLYGONOFFSETPROC)wglGetProcAddress("glPolygonOffset");
    glPrimitiveRestartIndex=(GLPRIMITIVERESTARTINDEXPROC)wglGetProcAddress("glPrimitiveRestartIndex");
    glProvokingVertex=(GLPROVOKINGVERTEXPROC)wglGetProcAddress("glProvokingVertex");
    glQueryCounter=(GLQUERYCOUNTERPROC)wglGetProcAddress("glQueryCounter");
    glReadBuffer=(GLREADBUFFERPROC)wglGetProcAddress("glReadBuffer");
    glReadPixels=(GLREADPIXELSPROC)wglGetProcAddress("glReadPixels");
    glRenderbufferStorage=(GLRENDERBUFFERSTORAGEPROC)wglGetProcAddress("glRenderbufferStorage");
    glRenderbufferStorageMultisample=(GLRENDERBUFFERSTORAGEMULTISAMPLEPROC)wglGetProcAddress("glRenderbufferStorageMultisample");
    glSampleCoverage=(GLSAMPLECOVERAGEPROC)wglGetProcAddress("glSampleCoverage");
    glSampleMaski=(GLSAMPLEMASKIPROC)wglGetProcAddress("glSampleMaski");
    glSamplerParameterIiv=(GLSAMPLERPARAMETERIIVPROC)wglGetProcAddress("glSamplerParameterIiv");
    glSamplerParameterIuiv=(GLSAMPLERPARAMETERIUIVPROC)wglGetProcAddress("glSamplerParameterIuiv");
    glSamplerParameterf=(GLSAMPLERPARAMETERFPROC)wglGetProcAddress("glSamplerParameterf");
    glSamplerParameterfv=(GLSAMPLERPARAMETERFVPROC)wglGetProcAddress("glSamplerParameterfv");
    glSamplerParameteri=(GLSAMPLERPARAMETERIPROC)wglGetProcAddress("glSamplerParameteri");
    glSamplerParameteriv=(GLSAMPLERPARAMETERIVPROC)wglGetProcAddress("glSamplerParameteriv");
    glScissor=(GLSCISSORPROC)wglGetProcAddress("glScissor");
    glSecondaryColorP3ui=(GLSECONDARYCOLORP3UIPROC)wglGetProcAddress("glSecondaryColorP3ui");
    glSecondaryColorP3uiv=(GLSECONDARYCOLORP3UIVPROC)wglGetProcAddress("glSecondaryColorP3uiv");
    glShaderSource=(GLSHADERSOURCEPROC)wglGetProcAddress("glShaderSource");
    glStencilFunc=(GLSTENCILFUNCPROC)wglGetProcAddress("glStencilFunc");
    glStencilFuncSeparate=(GLSTENCILFUNCSEPARATEPROC)wglGetProcAddress("glStencilFuncSeparate");
    glStencilMask=(GLSTENCILMASKPROC)wglGetProcAddress("glStencilMask");
    glStencilMaskSeparate=(GLSTENCILMASKSEPARATEPROC)wglGetProcAddress("glStencilMaskSeparate");
    glStencilOp=(GLSTENCILOPPROC)wglGetProcAddress("glStencilOp");
    glStencilOpSeparate=(GLSTENCILOPSEPARATEPROC)wglGetProcAddress("glStencilOpSeparate");
    glTexBuffer=(GLTEXBUFFERPROC)wglGetProcAddress("glTexBuffer");
    glTexCoordP1ui=(GLTEXCOORDP1UIPROC)wglGetProcAddress("glTexCoordP1ui");
    glTexCoordP1uiv=(GLTEXCOORDP1UIVPROC)wglGetProcAddress("glTexCoordP1uiv");
    glTexCoordP2ui=(GLTEXCOORDP2UIPROC)wglGetProcAddress("glTexCoordP2ui");
    glTexCoordP2uiv=(GLTEXCOORDP2UIVPROC)wglGetProcAddress("glTexCoordP2uiv");
    glTexCoordP3ui=(GLTEXCOORDP3UIPROC)wglGetProcAddress("glTexCoordP3ui");
    glTexCoordP3uiv=(GLTEXCOORDP3UIVPROC)wglGetProcAddress("glTexCoordP3uiv");
    glTexCoordP4ui=(GLTEXCOORDP4UIPROC)wglGetProcAddress("glTexCoordP4ui");
    glTexCoordP4uiv=(GLTEXCOORDP4UIVPROC)wglGetProcAddress("glTexCoordP4uiv");
    glTexImage1D=(GLTEXIMAGE1DPROC)wglGetProcAddress("glTexImage1D");
    glTexImage2D=(GLTEXIMAGE2DPROC)wglGetProcAddress("glTexImage2D");
    glTexImage2DMultisample=(GLTEXIMAGE2DMULTISAMPLEPROC)wglGetProcAddress("glTexImage2DMultisample");
    glTexImage3D=(GLTEXIMAGE3DPROC)wglGetProcAddress("glTexImage3D");
    glTexImage3DMultisample=(GLTEXIMAGE3DMULTISAMPLEPROC)wglGetProcAddress("glTexImage3DMultisample");
    glTexParameterIiv=(GLTEXPARAMETERIIVPROC)wglGetProcAddress("glTexParameterIiv");
    glTexParameterIuiv=(GLTEXPARAMETERIUIVPROC)wglGetProcAddress("glTexParameterIuiv");
    glTexParameterf=(GLTEXPARAMETERFPROC)wglGetProcAddress("glTexParameterf");
    glTexParameterfv=(GLTEXPARAMETERFVPROC)wglGetProcAddress("glTexParameterfv");
    glTexParameteri=(GLTEXPARAMETERIPROC)wglGetProcAddress("glTexParameteri");
    glTexParameteriv=(GLTEXPARAMETERIVPROC)wglGetProcAddress("glTexParameteriv");
    glTexSubImage1D=(GLTEXSUBIMAGE1DPROC)wglGetProcAddress("glTexSubImage1D");
    glTexSubImage2D=(GLTEXSUBIMAGE2DPROC)wglGetProcAddress("glTexSubImage2D");
    glTexSubImage3D=(GLTEXSUBIMAGE3DPROC)wglGetProcAddress("glTexSubImage3D");
    glTransformFeedbackVaryings=(GLTRANSFORMFEEDBACKVARYINGSPROC)wglGetProcAddress("glTransformFeedbackVaryings");
    glUniform1f=(GLUNIFORM1FPROC)wglGetProcAddress("glUniform1f");
    glUniform1fv=(GLUNIFORM1FVPROC)wglGetProcAddress("glUniform1fv");
    glUniform1i=(GLUNIFORM1IPROC)wglGetProcAddress("glUniform1i");
    glUniform1iv=(GLUNIFORM1IVPROC)wglGetProcAddress("glUniform1iv");
    glUniform1ui=(GLUNIFORM1UIPROC)wglGetProcAddress("glUniform1ui");
    glUniform1uiv=(GLUNIFORM1UIVPROC)wglGetProcAddress("glUniform1uiv");
    glUniform2f=(GLUNIFORM2FPROC)wglGetProcAddress("glUniform2f");
    glUniform2fv=(GLUNIFORM2FVPROC)wglGetProcAddress("glUniform2fv");
    glUniform2i=(GLUNIFORM2IPROC)wglGetProcAddress("glUniform2i");
    glUniform2iv=(GLUNIFORM2IVPROC)wglGetProcAddress("glUniform2iv");
    glUniform2ui=(GLUNIFORM2UIPROC)wglGetProcAddress("glUniform2ui");
    glUniform2uiv=(GLUNIFORM2UIVPROC)wglGetProcAddress("glUniform2uiv");
    glUniform3f=(GLUNIFORM3FPROC)wglGetProcAddress("glUniform3f");
    glUniform3fv=(GLUNIFORM3FVPROC)wglGetProcAddress("glUniform3fv");
    glUniform3i=(GLUNIFORM3IPROC)wglGetProcAddress("glUniform3i");
    glUniform3iv=(GLUNIFORM3IVPROC)wglGetProcAddress("glUniform3iv");
    glUniform3ui=(GLUNIFORM3UIPROC)wglGetProcAddress("glUniform3ui");
    glUniform3uiv=(GLUNIFORM3UIVPROC)wglGetProcAddress("glUniform3uiv");
    glUniform4f=(GLUNIFORM4FPROC)wglGetProcAddress("glUniform4f");
    glUniform4fv=(GLUNIFORM4FVPROC)wglGetProcAddress("glUniform4fv");
    glUniform4i=(GLUNIFORM4IPROC)wglGetProcAddress("glUniform4i");
    glUniform4iv=(GLUNIFORM4IVPROC)wglGetProcAddress("glUniform4iv");
    glUniform4ui=(GLUNIFORM4UIPROC)wglGetProcAddress("glUniform4ui");
    glUniform4uiv=(GLUNIFORM4UIVPROC)wglGetProcAddress("glUniform4uiv");
    glUniformBlockBinding=(GLUNIFORMBLOCKBINDINGPROC)wglGetProcAddress("glUniformBlockBinding");
    glUniformMatrix2fv=(GLUNIFORMMATRIX2FVPROC)wglGetProcAddress("glUniformMatrix2fv");
    glUniformMatrix2x3fv=(GLUNIFORMMATRIX2X3FVPROC)wglGetProcAddress("glUniformMatrix2x3fv");
    glUniformMatrix2x4fv=(GLUNIFORMMATRIX2X4FVPROC)wglGetProcAddress("glUniformMatrix2x4fv");
    glUniformMatrix3fv=(GLUNIFORMMATRIX3FVPROC)wglGetProcAddress("glUniformMatrix3fv");
    glUniformMatrix3x2fv=(GLUNIFORMMATRIX3X2FVPROC)wglGetProcAddress("glUniformMatrix3x2fv");
    glUniformMatrix3x4fv=(GLUNIFORMMATRIX3X4FVPROC)wglGetProcAddress("glUniformMatrix3x4fv");
    glUniformMatrix4fv=(GLUNIFORMMATRIX4FVPROC)wglGetProcAddress("glUniformMatrix4fv");
    glUniformMatrix4x2fv=(GLUNIFORMMATRIX4X2FVPROC)wglGetProcAddress("glUniformMatrix4x2fv");
    glUniformMatrix4x3fv=(GLUNIFORMMATRIX4X3FVPROC)wglGetProcAddress("glUniformMatrix4x3fv");
    glUnmapBuffer=(GLUNMAPBUFFERPROC)wglGetProcAddress("glUnmapBuffer");
    glUseProgram=(GLUSEPROGRAMPROC)wglGetProcAddress("glUseProgram");
    glValidateProgram=(GLVALIDATEPROGRAMPROC)wglGetProcAddress("glValidateProgram");
    glVertexAttrib1d=(GLVERTEXATTRIB1DPROC)wglGetProcAddress("glVertexAttrib1d");
    glVertexAttrib1dv=(GLVERTEXATTRIB1DVPROC)wglGetProcAddress("glVertexAttrib1dv");
    glVertexAttrib1f=(GLVERTEXATTRIB1FPROC)wglGetProcAddress("glVertexAttrib1f");
    glVertexAttrib1fv=(GLVERTEXATTRIB1FVPROC)wglGetProcAddress("glVertexAttrib1fv");
    glVertexAttrib1s=(GLVERTEXATTRIB1SPROC)wglGetProcAddress("glVertexAttrib1s");
    glVertexAttrib1sv=(GLVERTEXATTRIB1SVPROC)wglGetProcAddress("glVertexAttrib1sv");
    glVertexAttrib2d=(GLVERTEXATTRIB2DPROC)wglGetProcAddress("glVertexAttrib2d");
    glVertexAttrib2dv=(GLVERTEXATTRIB2DVPROC)wglGetProcAddress("glVertexAttrib2dv");
    glVertexAttrib2f=(GLVERTEXATTRIB2FPROC)wglGetProcAddress("glVertexAttrib2f");
    glVertexAttrib2fv=(GLVERTEXATTRIB2FVPROC)wglGetProcAddress("glVertexAttrib2fv");
    glVertexAttrib2s=(GLVERTEXATTRIB2SPROC)wglGetProcAddress("glVertexAttrib2s");
    glVertexAttrib2sv=(GLVERTEXATTRIB2SVPROC)wglGetProcAddress("glVertexAttrib2sv");
    glVertexAttrib3d=(GLVERTEXATTRIB3DPROC)wglGetProcAddress("glVertexAttrib3d");
    glVertexAttrib3dv=(GLVERTEXATTRIB3DVPROC)wglGetProcAddress("glVertexAttrib3dv");
    glVertexAttrib3f=(GLVERTEXATTRIB3FPROC)wglGetProcAddress("glVertexAttrib3f");
    glVertexAttrib3fv=(GLVERTEXATTRIB3FVPROC)wglGetProcAddress("glVertexAttrib3fv");
    glVertexAttrib3s=(GLVERTEXATTRIB3SPROC)wglGetProcAddress("glVertexAttrib3s");
    glVertexAttrib3sv=(GLVERTEXATTRIB3SVPROC)wglGetProcAddress("glVertexAttrib3sv");
    glVertexAttrib4Nbv=(GLVERTEXATTRIB4NBVPROC)wglGetProcAddress("glVertexAttrib4Nbv");
    glVertexAttrib4Niv=(GLVERTEXATTRIB4NIVPROC)wglGetProcAddress("glVertexAttrib4Niv");
    glVertexAttrib4Nsv=(GLVERTEXATTRIB4NSVPROC)wglGetProcAddress("glVertexAttrib4Nsv");
    glVertexAttrib4Nub=(GLVERTEXATTRIB4NUBPROC)wglGetProcAddress("glVertexAttrib4Nub");
    glVertexAttrib4Nubv=(GLVERTEXATTRIB4NUBVPROC)wglGetProcAddress("glVertexAttrib4Nubv");
    glVertexAttrib4Nuiv=(GLVERTEXATTRIB4NUIVPROC)wglGetProcAddress("glVertexAttrib4Nuiv");
    glVertexAttrib4Nusv=(GLVERTEXATTRIB4NUSVPROC)wglGetProcAddress("glVertexAttrib4Nusv");
    glVertexAttrib4bv=(GLVERTEXATTRIB4BVPROC)wglGetProcAddress("glVertexAttrib4bv");
    glVertexAttrib4d=(GLVERTEXATTRIB4DPROC)wglGetProcAddress("glVertexAttrib4d");
    glVertexAttrib4dv=(GLVERTEXATTRIB4DVPROC)wglGetProcAddress("glVertexAttrib4dv");
    glVertexAttrib4f=(GLVERTEXATTRIB4FPROC)wglGetProcAddress("glVertexAttrib4f");
    glVertexAttrib4fv=(GLVERTEXATTRIB4FVPROC)wglGetProcAddress("glVertexAttrib4fv");
    glVertexAttrib4iv=(GLVERTEXATTRIB4IVPROC)wglGetProcAddress("glVertexAttrib4iv");
    glVertexAttrib4s=(GLVERTEXATTRIB4SPROC)wglGetProcAddress("glVertexAttrib4s");
    glVertexAttrib4sv=(GLVERTEXATTRIB4SVPROC)wglGetProcAddress("glVertexAttrib4sv");
    glVertexAttrib4ubv=(GLVERTEXATTRIB4UBVPROC)wglGetProcAddress("glVertexAttrib4ubv");
    glVertexAttrib4uiv=(GLVERTEXATTRIB4UIVPROC)wglGetProcAddress("glVertexAttrib4uiv");
    glVertexAttrib4usv=(GLVERTEXATTRIB4USVPROC)wglGetProcAddress("glVertexAttrib4usv");
    glVertexAttribDivisor=(GLVERTEXATTRIBDIVISORPROC)wglGetProcAddress("glVertexAttribDivisor");
    glVertexAttribI1i=(GLVERTEXATTRIBI1IPROC)wglGetProcAddress("glVertexAttribI1i");
    glVertexAttribI1iv=(GLVERTEXATTRIBI1IVPROC)wglGetProcAddress("glVertexAttribI1iv");
    glVertexAttribI1ui=(GLVERTEXATTRIBI1UIPROC)wglGetProcAddress("glVertexAttribI1ui");
    glVertexAttribI1uiv=(GLVERTEXATTRIBI1UIVPROC)wglGetProcAddress("glVertexAttribI1uiv");
    glVertexAttribI2i=(GLVERTEXATTRIBI2IPROC)wglGetProcAddress("glVertexAttribI2i");
    glVertexAttribI2iv=(GLVERTEXATTRIBI2IVPROC)wglGetProcAddress("glVertexAttribI2iv");
    glVertexAttribI2ui=(GLVERTEXATTRIBI2UIPROC)wglGetProcAddress("glVertexAttribI2ui");
    glVertexAttribI2uiv=(GLVERTEXATTRIBI2UIVPROC)wglGetProcAddress("glVertexAttribI2uiv");
    glVertexAttribI3i=(GLVERTEXATTRIBI3IPROC)wglGetProcAddress("glVertexAttribI3i");
    glVertexAttribI3iv=(GLVERTEXATTRIBI3IVPROC)wglGetProcAddress("glVertexAttribI3iv");
    glVertexAttribI3ui=(GLVERTEXATTRIBI3UIPROC)wglGetProcAddress("glVertexAttribI3ui");
    glVertexAttribI3uiv=(GLVERTEXATTRIBI3UIVPROC)wglGetProcAddress("glVertexAttribI3uiv");
    glVertexAttribI4bv=(GLVERTEXATTRIBI4BVPROC)wglGetProcAddress("glVertexAttribI4bv");
    glVertexAttribI4i=(GLVERTEXATTRIBI4IPROC)wglGetProcAddress("glVertexAttribI4i");
    glVertexAttribI4iv=(GLVERTEXATTRIBI4IVPROC)wglGetProcAddress("glVertexAttribI4iv");
    glVertexAttribI4sv=(GLVERTEXATTRIBI4SVPROC)wglGetProcAddress("glVertexAttribI4sv");
    glVertexAttribI4ubv=(GLVERTEXATTRIBI4UBVPROC)wglGetProcAddress("glVertexAttribI4ubv");
    glVertexAttribI4ui=(GLVERTEXATTRIBI4UIPROC)wglGetProcAddress("glVertexAttribI4ui");
    glVertexAttribI4uiv=(GLVERTEXATTRIBI4UIVPROC)wglGetProcAddress("glVertexAttribI4uiv");
    glVertexAttribI4usv=(GLVERTEXATTRIBI4USVPROC)wglGetProcAddress("glVertexAttribI4usv");
    glVertexAttribIPointer=(GLVERTEXATTRIBIPOINTERPROC)wglGetProcAddress("glVertexAttribIPointer");
    glVertexAttribP1ui=(GLVERTEXATTRIBP1UIPROC)wglGetProcAddress("glVertexAttribP1ui");
    glVertexAttribP1uiv=(GLVERTEXATTRIBP1UIVPROC)wglGetProcAddress("glVertexAttribP1uiv");
    glVertexAttribP2ui=(GLVERTEXATTRIBP2UIPROC)wglGetProcAddress("glVertexAttribP2ui");
    glVertexAttribP2uiv=(GLVERTEXATTRIBP2UIVPROC)wglGetProcAddress("glVertexAttribP2uiv");
    glVertexAttribP3ui=(GLVERTEXATTRIBP3UIPROC)wglGetProcAddress("glVertexAttribP3ui");
    glVertexAttribP3uiv=(GLVERTEXATTRIBP3UIVPROC)wglGetProcAddress("glVertexAttribP3uiv");
    glVertexAttribP4ui=(GLVERTEXATTRIBP4UIPROC)wglGetProcAddress("glVertexAttribP4ui");
    glVertexAttribP4uiv=(GLVERTEXATTRIBP4UIVPROC)wglGetProcAddress("glVertexAttribP4uiv");
    glVertexAttribPointer=(GLVERTEXATTRIBPOINTERPROC)wglGetProcAddress("glVertexAttribPointer");
    glVertexP2ui=(GLVERTEXP2UIPROC)wglGetProcAddress("glVertexP2ui");
    glVertexP2uiv=(GLVERTEXP2UIVPROC)wglGetProcAddress("glVertexP2uiv");
    glVertexP3ui=(GLVERTEXP3UIPROC)wglGetProcAddress("glVertexP3ui");
    glVertexP3uiv=(GLVERTEXP3UIVPROC)wglGetProcAddress("glVertexP3uiv");
    glVertexP4ui=(GLVERTEXP4UIPROC)wglGetProcAddress("glVertexP4ui");
    glVertexP4uiv=(GLVERTEXP4UIVPROC)wglGetProcAddress("glVertexP4uiv");
    glViewport=(GLVIEWPORTPROC)wglGetProcAddress("glViewport");
    glWaitSync=(GLWAITSYNCPROC)wglGetProcAddress("glWaitSync");
}
